# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'site_categorizer_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_site_categoriserDockWidgetBase(object):
    def setupUi(self, site_categoriserDockWidgetBase):
        site_categoriserDockWidgetBase.setObjectName("site_categoriserDockWidgetBase")
        site_categoriserDockWidgetBase.resize(966, 677)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_widget = QtWidgets.QWidget(self.dockWidgetContents)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.main_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.secWidget = sectionWidget(self.frame)
        self.secWidget.setObjectName("secWidget")
        self.horizontalLayout_2.addWidget(self.secWidget)
        self.chWidget = chainageWidget(self.frame)
        self.chWidget.setObjectName("chWidget")
        self.horizontalLayout_2.addWidget(self.chWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.oneWayBox = QtWidgets.QCheckBox(self.frame)
        self.oneWayBox.setObjectName("oneWayBox")
        self.horizontalLayout_3.addWidget(self.oneWayBox)
        self.noteEdit = QtWidgets.QLineEdit(self.frame)
        self.noteEdit.setObjectName("noteEdit")
        self.horizontalLayout_3.addWidget(self.noteEdit)
        self.checkedBox = QtWidgets.QCheckBox(self.frame)
        self.checkedBox.setObjectName("checkedBox")
        self.horizontalLayout_3.addWidget(self.checkedBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.otherEventsAddButton = QtWidgets.QPushButton(self.tab)
        self.otherEventsAddButton.setObjectName("otherEventsAddButton")
        self.verticalLayout_5.addWidget(self.otherEventsAddButton)
        self.otherEventsView = focusedTableView(self.tab)
        self.otherEventsView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.otherEventsView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.otherEventsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.otherEventsView.setObjectName("otherEventsView")
        self.verticalLayout_5.addWidget(self.otherEventsView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.addBox = QtWidgets.QComboBox(self.tab_4)
        self.addBox.setObjectName("addBox")
        self.horizontalLayout.addWidget(self.addBox)
        self.addJcButton = QtWidgets.QPushButton(self.tab_4)
        self.addJcButton.setObjectName("addJcButton")
        self.horizontalLayout.addWidget(self.addJcButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.jcView = QtWidgets.QTableView(self.tab_4)
        self.jcView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.jcView.setObjectName("jcView")
        self.verticalLayout_6.addWidget(self.jcView)
        self.tabWidget.addTab(self.tab_4, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.policyView = QtWidgets.QTableView(self.widget)
        self.policyView.setObjectName("policyView")
        self.verticalLayout_4.addWidget(self.policyView)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
